(function(){
const KEY='myStyleWardrobeV2';
const DETAILS={composition:'Полиэстер — 65%, вискоза — 34%, эластан — 1%',fabric:'Трикотаж',lining:'Без подкладки',season:'Мульти',modelSize:'S INT',length:'45 см (S INT)',sleeveLength:'20 см (S INT)',modelMeasurements:'81–61–89',modelHeight:'174 см',color:'Синий',pattern:'Полоска',collar:'Отложной'};
const isPolo=x=>{if(!x)return false;const n=String(x.name||'').trim().toLowerCase();const c=String(x.color||'').toLowerCase();const f=String(x.fit||'').toLowerCase();return n.includes('поло')||n.includes('polo')||(c.includes('синий')&&f.includes('прям'))};
function read(){try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch(e){return[]}}
function patch(){const w=read();let changed=false;w.forEach(x=>{if(isPolo(x)){x.details=DETAILS;x.note='Синий трикотажный поло в полоску с отложным воротником. Состав: полиэстер 65%, вискоза 34%, эластан 1%. Мягкий эластичный материал без подкладки; длина 45 см, рукав 20 см. Модель 174 см, размер S INT.';if(!x.score||x.score==='—')x.score='8.5';changed=true}});if(changed)localStorage.setItem(KEY,JSON.stringify(w));}
function esc(v){return String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]))}
function showPolo(i){const w=read(),x=w[i];if(!isPolo(x))return false;const d=x.details||DETAILS;const box=document.getElementById('modalContent');const modal=document.getElementById('modal');if(!box||!modal)return false;box.innerHTML='<span class="tag good">УЖЕ ЕСТЬ В ГАРДЕРОБЕ</span><h2>'+esc(x.name)+'</h2><img src="'+esc(x.img||'')+'" style="width:100%;max-height:360px;object-fit:contain;border-radius:14px;background:#f2efea"><div class="rule"><b>'+esc(x.score||'8.5')+'/10 — персонально для тебя</b><span>'+esc(x.note||'Синий трикотажный поло в полоску с отложным воротником.')+'</span></div><div class="rule"><b>Характеристики</b><span><b>Состав:</b> '+d.composition+'<br><b>Тип ткани:</b> '+d.fabric+'<br><b>Материал подкладки:</b> '+d.lining+'<br><b>Сезон:</b> '+d.season+'<br><b>Размер товара на модели:</b> '+d.modelSize+'<br><b>Длина:</b> '+d.length+'<br><b>Длина рукава:</b> '+d.sleeveLength+'<br><b>Параметры модели:</b> '+d.modelMeasurements+'<br><b>Рост модели на фото:</b> '+d.modelHeight+'<br><b>Цвет:</b> '+d.color+'<br><b>Узор:</b> '+d.pattern+'<br><b>Вырез / воротник:</b> '+d.collar+'</span></div><div class="rule"><b>С чем носить</b><span>Лучше всего — с однотонным низом: прямыми джинсами, wide-leg или спокойными брюками. Полоску оставляем главным акцентом верха.</span></div>';modal.classList.add('show');return true}
function install(){patch();const previous=window.detail;if(typeof previous==='function'&&!previous.__poloFix){const wrapped=function(i){if(showPolo(i))return;return previous(i)};wrapped.__poloFix=true;window.detail=wrapped;}else if(typeof window.detail!=='function'){window.detail=showPolo;} }
install();setTimeout(install,100);setTimeout(install,500);setTimeout(install,1500);setTimeout(install,3000);
})();