/* wardrobe editor is loaded by the page when available */
(function(){
const KEY='myStyleWardrobeV2';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}};
const write=w=>{localStorage.setItem(KEY,JSON.stringify(w));if(typeof window.renderW==='function')window.renderW();};
function close(){document.getElementById('weModal')?.classList.remove('show')}
function shell(html){let m=document.getElementById('weModal');if(!m){m=document.createElement('div');m.id='weModal';document.body.appendChild(m)}m.innerHTML='<div class="weBox"><button class="weClose" id="weClose">×</button>'+html+'</div>';m.classList.add('show');m.querySelector('#weClose').onclick=close;return m}
function add(){const m=shell('<div class="weKicker">НОВАЯ ВЕЩЬ</div><h2>Добавить в гардероб</h2><p class="weMuted">Загрузи оригинальное фото. Оно останется в твоём браузере и будет использоваться в карточке.</p><label class="weDrop"><input id="newFile" type="file" accept="image/*"><b>Выбрать фотографию</b><span>Можно загрузить фото с телефона или компьютера</span></label><img id="newPreview" class="wePreview" hidden><div class="weForm"><label>Название<input id="newName" placeholder="Например, голубые straight джинсы"></label><label>Категория<select id="newCat"><option>Верх</option><option>Низ</option><option>Второй слой</option><option>Верхняя одежда</option><option>Обувь</option><option>Сумки</option><option>Аксессуары</option></select></label><label>Цвет<input id="newColor" placeholder="Молочный, голубой…"></label><label>Фасон / посадка<input id="newFit" placeholder="Straight, облегающий…"></label><label>Оценка<input id="newScore" type="number" min="0" max="10" step="0.1" placeholder="8.7"></label><label class="wide">Комментарий<textarea id="newNote" placeholder="Что важно знать об этой вещи"></textarea></label></div><div class="weActions"><button class="weSecondary" id="cancel">Отмена</button><button class="wePrimary" id="saveNew">Добавить вещь</button></div>');
m.querySelector('#cancel').onclick=close;m.querySelector('#newFile').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{m.querySelector('#newPreview').src=r.result;m.querySelector('#newPreview').hidden=false};r.readAsDataURL(f)};m.querySelector('#saveNew').onclick=()=>{const f=m.querySelector('#newFile').files[0],name=m.querySelector('#newName').value.trim();if(!name)return alert('Укажи название вещи');if(!f)return alert('Загрузи фотографию вещи');const r=new FileReader();r.onload=()=>{const w=read();w.push({id:Date.now().toString(36),name,cat:m.querySelector('#newCat').value,color:m.querySelector('#newColor').value||'—',fit:m.querySelector('#newFit').value||'—',score:m.querySelector('#newScore').value||'—',note:m.querySelector('#newNote').value||'Вещь добавлена в мой гардероб.',img:r.result});try{write(w);close()}catch{alert('Фото слишком большое для хранения в браузере. Выбери немного меньшее фото.')}};r.readAsDataURL(f)} }
function edit(i){const w=read(),x=w[i];if(!x)return;const m=shell('<div class="weKicker">МОЯ ВЕЩЬ</div><h2>Редактировать карточку</h2><div class="wePhoto"><img id="editPreview" src="'+x.img+'"><label class="weUpload">Заменить фото<input id="editFile" type="file" accept="image/*"></label></div><div class="weForm"><label>Название<input id="editName" value="'+esc(x.name)+'"></label><label>Категория<select id="editCat"><option>Верх</option><option>Низ</option><option>Второй слой</option><option>Верхняя одежда</option><option>Обувь</option><option>Сумки</option><option>Аксессуары</option></select></label><label>Цвет<input id="editColor" value="'+esc(x.color||'')+'"></label><label>Фасон / посадка<input id="editFit" value="'+esc(x.fit||'')+'"></label><label>Оценка<input id="editScore" type="number" min="0" max="10" step="0.1" value="'+(x.score==='—'?'':esc(x.score))+'"></label><label class="wide">Комментарий<textarea id="editNote">'+esc(x.note||'')+'</textarea></label></div><div class="weActions"><button class="weSecondary" id="cancel">Отмена</button><button class="wePrimary" id="saveEdit">Сохранить</button></div>');m.querySelector('#editCat').value=x.cat||'Верх';m.querySelector('#cancel').onclick=close;m.querySelector('#editFile').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>m.querySelector('#editPreview').src=r.result;r.readAsDataURL(f)};m.querySelector('#saveEdit').onclick=()=>{x.name=m.querySelector('#editName').value.trim()||x.name;x.cat=m.querySelector('#editCat').value;x.color=m.querySelector('#editColor').value||'—';x.fit=m.querySelector('#editFit').value||'—';x.score=m.querySelector('#editScore').value||'—';x.note=m.querySelector('#editNote').value||'Вещь сохранена в моём гардеробе.';const f=m.querySelector('#editFile').files[0];const done=()=>{w[i]=x;try{write(w);close()}catch{alert('Фото слишком большое для хранения в браузере.')}};if(f){const r=new FileReader();r.onload=()=>{x.img=r.result;done()};r.readAsDataURL(f)}else done()}}
function remove(i){if(!confirm('Удалить эту вещь из гардероба?'))return;const w=read();w.splice(i,1);write(w)}
function enhance(){if(document.getElementById('weStyle'))return;const st=document.createElement('style');st.id='weStyle';st.textContent='#weModal{display:none;position:fixed;inset:0;z-index:9999;background:rgba(25,23,20,.58);align-items:center;justify-content:center;padding:16px}#weModal.show{display:flex}.weBox{width:min(620px,100%);max-height:92vh;overflow:auto;background:#fff;border-radius:24px;padding:22px;color:#252421;border:1px solid #e5ddd4}.weClose{float:right;width:38px;height:38px;border:1px solid #ddd5cc;background:#fff;border-radius:50%;font-size:22px}.weKicker{font-size:9px;letter-spacing:.18em;color:#8b8278;font-weight:700}.weBox h2{font-size:28px;letter-spacing:-.04em;margin:8px 0 14px}.weMuted{font-size:11px;color:#847b72;line-height:1.5}.wePhoto{position:relative;background:#f1eee9;border-radius:16px;display:grid;place-items:center;overflow:hidden;margin:12px 0 14px}.wePhoto img{max-width:100%;max-height:390px;width:100%;height:auto;object-fit:contain}.weUpload{position:absolute;right:12px;bottom:12px;background:#fff;border:1px solid #ddd5cc;border-radius:999px;padding:10px 13px;font-size:11px;cursor:pointer}.weUpload input{display:none}.weForm{display:grid;grid-template-columns:1fr 1fr;gap:10px}.weForm label{font-size:10px;color:#756d64}.weForm .wide{grid-column:1/-1}.weForm input,.weForm select,.weForm textarea{display:block;width:100%;margin-top:5px;border:1px solid #ded7cf;border-radius:11px;padding:11px;background:#fff;color:#252421}.weForm textarea{min-height:85px}.weActions{display:flex;justify-content:flex-end;gap:8px;margin-top:16px}.wePrimary,.weSecondary{border-radius:11px;padding:11px 16px;border:1px solid #282724;cursor:pointer}.wePrimary{background:#282724;color:#fff}.weSecondary{background:#fff}.weDrop{border:1px dashed #cfc5bb;border-radius:15px;padding:16px;display:flex;gap:12px;align-items:center;margin:12px 0;cursor:pointer}.weDrop input{max-width:190px}.weDrop span{font-size:10px;color:#8a8178}.wePreview{width:100%;max-height:250px;object-fit:contain;border-radius:14px;background:#f1eee9;margin-bottom:12px}@media(max-width:600px){.weForm{grid-template-columns:1fr}.weForm .wide{grid-column:auto}}';document.head.appendChild(st);
const head=document.querySelector('#wardrobe .head');if(head&&!head.querySelector('[data-we-add]')){const b=document.createElement('button');b.className='btn';b.dataset.weAdd='1';b.textContent='+ Добавить вещь';b.onclick=add;head.appendChild(b)}
const oldRender=window.renderW;window.renderW=function(){if(oldRender)oldRender();setTimeout(decorate,0)};decorate();
}
function decorate(){const w=read();document.querySelectorAll('#wardrobeGrid .item').forEach((card,n)=>{const visible=w.filter(x=>window.F==='Все'||x.cat===window.F),x=visible[n],i=w.indexOf(x);if(!x)return;let box=card.querySelector('.itemBtns');if(!box)return;box.querySelectorAll('[data-we]').forEach(b=>b.remove());const b=document.createElement('button');b.className='pill';b.dataset.we='1';b.textContent='Редактировать';b.onclick=()=>edit(i);box.prepend(b)})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',enhance);else enhance();
window.WardrobeEditor={add,edit,remove};
})();